// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

#ifndef PROTOBUF_meta_2eproto__INCLUDED
#define PROTOBUF_meta_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_meta_2eproto();
void protobuf_AssignDesc_meta_2eproto();
void protobuf_ShutdownFile_meta_2eproto();

class Package;

// ===================================================================

class Package : public ::google::protobuf::Message {
 public:
  Package();
  virtual ~Package();
  
  Package(const Package& from);
  
  inline Package& operator=(const Package& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Package& default_instance();
  
  void Swap(Package* other);
  
  // implements Message ----------------------------------------------
  
  Package* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Package& from);
  void MergeFrom(const Package& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string virtualPath = 1;
  inline bool has_virtualpath() const;
  inline void clear_virtualpath();
  static const int kVirtualPathFieldNumber = 1;
  inline const ::std::string& virtualpath() const;
  inline void set_virtualpath(const ::std::string& value);
  inline void set_virtualpath(const char* value);
  inline void set_virtualpath(const char* value, size_t size);
  inline ::std::string* mutable_virtualpath();
  inline ::std::string* release_virtualpath();
  
  // optional int32 num = 2;
  inline bool has_num() const;
  inline void clear_num();
  static const int kNumFieldNumber = 2;
  inline ::google::protobuf::int32 num() const;
  inline void set_num(::google::protobuf::int32 value);
  
  // optional string realFullPath = 3;
  inline bool has_realfullpath() const;
  inline void clear_realfullpath();
  static const int kRealFullPathFieldNumber = 3;
  inline const ::std::string& realfullpath() const;
  inline void set_realfullpath(const ::std::string& value);
  inline void set_realfullpath(const char* value);
  inline void set_realfullpath(const char* value, size_t size);
  inline ::std::string* mutable_realfullpath();
  inline ::std::string* release_realfullpath();
  
  // optional bool isDir = 4;
  inline bool has_isdir() const;
  inline void clear_isdir();
  static const int kIsDirFieldNumber = 4;
  inline bool isdir() const;
  inline void set_isdir(bool value);
  
  // repeated string listItem = 5;
  inline int listitem_size() const;
  inline void clear_listitem();
  static const int kListItemFieldNumber = 5;
  inline const ::std::string& listitem(int index) const;
  inline ::std::string* mutable_listitem(int index);
  inline void set_listitem(int index, const ::std::string& value);
  inline void set_listitem(int index, const char* value);
  inline void set_listitem(int index, const char* value, size_t size);
  inline ::std::string* add_listitem();
  inline void add_listitem(const ::std::string& value);
  inline void add_listitem(const char* value);
  inline void add_listitem(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& listitem() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_listitem();
  
  // optional int32 openMode = 6;
  inline bool has_openmode() const;
  inline void clear_openmode();
  static const int kOpenModeFieldNumber = 6;
  inline ::google::protobuf::int32 openmode() const;
  inline void set_openmode(::google::protobuf::int32 value);
  
  // optional int32 mode = 7;
  inline bool has_mode() const;
  inline void clear_mode();
  static const int kModeFieldNumber = 7;
  inline ::google::protobuf::int32 mode() const;
  inline void set_mode(::google::protobuf::int32 value);
  
  // optional int32 Operation = 8;
  inline bool has_operation() const;
  inline void clear_operation();
  static const int kOperationFieldNumber = 8;
  inline ::google::protobuf::int32 operation() const;
  inline void set_operation(::google::protobuf::int32 value);
  
  // optional int32 replicaNo = 9;
  inline bool has_replicano() const;
  inline void clear_replicano();
  static const int kReplicaNoFieldNumber = 9;
  inline ::google::protobuf::int32 replicano() const;
  inline void set_replicano(::google::protobuf::int32 value);
  
  // optional string opcode = 10;
  inline bool has_opcode() const;
  inline void clear_opcode();
  static const int kOpcodeFieldNumber = 10;
  inline const ::std::string& opcode() const;
  inline void set_opcode(const ::std::string& value);
  inline void set_opcode(const char* value);
  inline void set_opcode(const char* value, size_t size);
  inline ::std::string* mutable_opcode();
  inline ::std::string* release_opcode();
  
  // optional string rcode = 11;
  inline bool has_rcode() const;
  inline void clear_rcode();
  static const int kRcodeFieldNumber = 11;
  inline const ::std::string& rcode() const;
  inline void set_rcode(const ::std::string& value);
  inline void set_rcode(const char* value);
  inline void set_rcode(const char* value, size_t size);
  inline ::std::string* mutable_rcode();
  inline ::std::string* release_rcode();
  
  // optional uint32 migrateInst = 12;
  inline bool has_migrateinst() const;
  inline void clear_migrateinst();
  static const int kMigrateInstFieldNumber = 12;
  inline ::google::protobuf::uint32 migrateinst() const;
  inline void set_migrateinst(::google::protobuf::uint32 value);
  
  // optional uint64 targetZHT = 13;
  inline bool has_targetzht() const;
  inline void clear_targetzht();
  static const int kTargetZHTFieldNumber = 13;
  inline ::google::protobuf::uint64 targetzht() const;
  inline void set_targetzht(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:Package)
 private:
  inline void set_has_virtualpath();
  inline void clear_has_virtualpath();
  inline void set_has_num();
  inline void clear_has_num();
  inline void set_has_realfullpath();
  inline void clear_has_realfullpath();
  inline void set_has_isdir();
  inline void clear_has_isdir();
  inline void set_has_openmode();
  inline void clear_has_openmode();
  inline void set_has_mode();
  inline void clear_has_mode();
  inline void set_has_operation();
  inline void clear_has_operation();
  inline void set_has_replicano();
  inline void clear_has_replicano();
  inline void set_has_opcode();
  inline void clear_has_opcode();
  inline void set_has_rcode();
  inline void clear_has_rcode();
  inline void set_has_migrateinst();
  inline void clear_has_migrateinst();
  inline void set_has_targetzht();
  inline void clear_has_targetzht();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* virtualpath_;
  ::std::string* realfullpath_;
  ::google::protobuf::int32 num_;
  bool isdir_;
  ::google::protobuf::RepeatedPtrField< ::std::string> listitem_;
  ::google::protobuf::int32 openmode_;
  ::google::protobuf::int32 mode_;
  ::google::protobuf::int32 operation_;
  ::google::protobuf::int32 replicano_;
  ::std::string* opcode_;
  ::std::string* rcode_;
  ::google::protobuf::uint64 targetzht_;
  ::google::protobuf::uint32 migrateinst_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(13 + 31) / 32];
  
  friend void  protobuf_AddDesc_meta_2eproto();
  friend void protobuf_AssignDesc_meta_2eproto();
  friend void protobuf_ShutdownFile_meta_2eproto();
  
  void InitAsDefaultInstance();
  static Package* default_instance_;
};
// ===================================================================


// ===================================================================

// Package

// optional string virtualPath = 1;
inline bool Package::has_virtualpath() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Package::set_has_virtualpath() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Package::clear_has_virtualpath() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Package::clear_virtualpath() {
  if (virtualpath_ != &::google::protobuf::internal::kEmptyString) {
    virtualpath_->clear();
  }
  clear_has_virtualpath();
}
inline const ::std::string& Package::virtualpath() const {
  return *virtualpath_;
}
inline void Package::set_virtualpath(const ::std::string& value) {
  set_has_virtualpath();
  if (virtualpath_ == &::google::protobuf::internal::kEmptyString) {
    virtualpath_ = new ::std::string;
  }
  virtualpath_->assign(value);
}
inline void Package::set_virtualpath(const char* value) {
  set_has_virtualpath();
  if (virtualpath_ == &::google::protobuf::internal::kEmptyString) {
    virtualpath_ = new ::std::string;
  }
  virtualpath_->assign(value);
}
inline void Package::set_virtualpath(const char* value, size_t size) {
  set_has_virtualpath();
  if (virtualpath_ == &::google::protobuf::internal::kEmptyString) {
    virtualpath_ = new ::std::string;
  }
  virtualpath_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_virtualpath() {
  set_has_virtualpath();
  if (virtualpath_ == &::google::protobuf::internal::kEmptyString) {
    virtualpath_ = new ::std::string;
  }
  return virtualpath_;
}
inline ::std::string* Package::release_virtualpath() {
  clear_has_virtualpath();
  if (virtualpath_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = virtualpath_;
    virtualpath_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional int32 num = 2;
inline bool Package::has_num() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Package::set_has_num() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Package::clear_has_num() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Package::clear_num() {
  num_ = 0;
  clear_has_num();
}
inline ::google::protobuf::int32 Package::num() const {
  return num_;
}
inline void Package::set_num(::google::protobuf::int32 value) {
  set_has_num();
  num_ = value;
}

// optional string realFullPath = 3;
inline bool Package::has_realfullpath() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Package::set_has_realfullpath() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Package::clear_has_realfullpath() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Package::clear_realfullpath() {
  if (realfullpath_ != &::google::protobuf::internal::kEmptyString) {
    realfullpath_->clear();
  }
  clear_has_realfullpath();
}
inline const ::std::string& Package::realfullpath() const {
  return *realfullpath_;
}
inline void Package::set_realfullpath(const ::std::string& value) {
  set_has_realfullpath();
  if (realfullpath_ == &::google::protobuf::internal::kEmptyString) {
    realfullpath_ = new ::std::string;
  }
  realfullpath_->assign(value);
}
inline void Package::set_realfullpath(const char* value) {
  set_has_realfullpath();
  if (realfullpath_ == &::google::protobuf::internal::kEmptyString) {
    realfullpath_ = new ::std::string;
  }
  realfullpath_->assign(value);
}
inline void Package::set_realfullpath(const char* value, size_t size) {
  set_has_realfullpath();
  if (realfullpath_ == &::google::protobuf::internal::kEmptyString) {
    realfullpath_ = new ::std::string;
  }
  realfullpath_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_realfullpath() {
  set_has_realfullpath();
  if (realfullpath_ == &::google::protobuf::internal::kEmptyString) {
    realfullpath_ = new ::std::string;
  }
  return realfullpath_;
}
inline ::std::string* Package::release_realfullpath() {
  clear_has_realfullpath();
  if (realfullpath_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = realfullpath_;
    realfullpath_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional bool isDir = 4;
inline bool Package::has_isdir() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Package::set_has_isdir() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Package::clear_has_isdir() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Package::clear_isdir() {
  isdir_ = false;
  clear_has_isdir();
}
inline bool Package::isdir() const {
  return isdir_;
}
inline void Package::set_isdir(bool value) {
  set_has_isdir();
  isdir_ = value;
}

// repeated string listItem = 5;
inline int Package::listitem_size() const {
  return listitem_.size();
}
inline void Package::clear_listitem() {
  listitem_.Clear();
}
inline const ::std::string& Package::listitem(int index) const {
  return listitem_.Get(index);
}
inline ::std::string* Package::mutable_listitem(int index) {
  return listitem_.Mutable(index);
}
inline void Package::set_listitem(int index, const ::std::string& value) {
  listitem_.Mutable(index)->assign(value);
}
inline void Package::set_listitem(int index, const char* value) {
  listitem_.Mutable(index)->assign(value);
}
inline void Package::set_listitem(int index, const char* value, size_t size) {
  listitem_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::add_listitem() {
  return listitem_.Add();
}
inline void Package::add_listitem(const ::std::string& value) {
  listitem_.Add()->assign(value);
}
inline void Package::add_listitem(const char* value) {
  listitem_.Add()->assign(value);
}
inline void Package::add_listitem(const char* value, size_t size) {
  listitem_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Package::listitem() const {
  return listitem_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Package::mutable_listitem() {
  return &listitem_;
}

// optional int32 openMode = 6;
inline bool Package::has_openmode() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Package::set_has_openmode() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Package::clear_has_openmode() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Package::clear_openmode() {
  openmode_ = 0;
  clear_has_openmode();
}
inline ::google::protobuf::int32 Package::openmode() const {
  return openmode_;
}
inline void Package::set_openmode(::google::protobuf::int32 value) {
  set_has_openmode();
  openmode_ = value;
}

// optional int32 mode = 7;
inline bool Package::has_mode() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Package::set_has_mode() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Package::clear_has_mode() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Package::clear_mode() {
  mode_ = 0;
  clear_has_mode();
}
inline ::google::protobuf::int32 Package::mode() const {
  return mode_;
}
inline void Package::set_mode(::google::protobuf::int32 value) {
  set_has_mode();
  mode_ = value;
}

// optional int32 Operation = 8;
inline bool Package::has_operation() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Package::set_has_operation() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Package::clear_has_operation() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Package::clear_operation() {
  operation_ = 0;
  clear_has_operation();
}
inline ::google::protobuf::int32 Package::operation() const {
  return operation_;
}
inline void Package::set_operation(::google::protobuf::int32 value) {
  set_has_operation();
  operation_ = value;
}

// optional int32 replicaNo = 9;
inline bool Package::has_replicano() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Package::set_has_replicano() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Package::clear_has_replicano() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Package::clear_replicano() {
  replicano_ = 0;
  clear_has_replicano();
}
inline ::google::protobuf::int32 Package::replicano() const {
  return replicano_;
}
inline void Package::set_replicano(::google::protobuf::int32 value) {
  set_has_replicano();
  replicano_ = value;
}

// optional string opcode = 10;
inline bool Package::has_opcode() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Package::set_has_opcode() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Package::clear_has_opcode() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Package::clear_opcode() {
  if (opcode_ != &::google::protobuf::internal::kEmptyString) {
    opcode_->clear();
  }
  clear_has_opcode();
}
inline const ::std::string& Package::opcode() const {
  return *opcode_;
}
inline void Package::set_opcode(const ::std::string& value) {
  set_has_opcode();
  if (opcode_ == &::google::protobuf::internal::kEmptyString) {
    opcode_ = new ::std::string;
  }
  opcode_->assign(value);
}
inline void Package::set_opcode(const char* value) {
  set_has_opcode();
  if (opcode_ == &::google::protobuf::internal::kEmptyString) {
    opcode_ = new ::std::string;
  }
  opcode_->assign(value);
}
inline void Package::set_opcode(const char* value, size_t size) {
  set_has_opcode();
  if (opcode_ == &::google::protobuf::internal::kEmptyString) {
    opcode_ = new ::std::string;
  }
  opcode_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_opcode() {
  set_has_opcode();
  if (opcode_ == &::google::protobuf::internal::kEmptyString) {
    opcode_ = new ::std::string;
  }
  return opcode_;
}
inline ::std::string* Package::release_opcode() {
  clear_has_opcode();
  if (opcode_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = opcode_;
    opcode_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string rcode = 11;
inline bool Package::has_rcode() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Package::set_has_rcode() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Package::clear_has_rcode() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Package::clear_rcode() {
  if (rcode_ != &::google::protobuf::internal::kEmptyString) {
    rcode_->clear();
  }
  clear_has_rcode();
}
inline const ::std::string& Package::rcode() const {
  return *rcode_;
}
inline void Package::set_rcode(const ::std::string& value) {
  set_has_rcode();
  if (rcode_ == &::google::protobuf::internal::kEmptyString) {
    rcode_ = new ::std::string;
  }
  rcode_->assign(value);
}
inline void Package::set_rcode(const char* value) {
  set_has_rcode();
  if (rcode_ == &::google::protobuf::internal::kEmptyString) {
    rcode_ = new ::std::string;
  }
  rcode_->assign(value);
}
inline void Package::set_rcode(const char* value, size_t size) {
  set_has_rcode();
  if (rcode_ == &::google::protobuf::internal::kEmptyString) {
    rcode_ = new ::std::string;
  }
  rcode_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Package::mutable_rcode() {
  set_has_rcode();
  if (rcode_ == &::google::protobuf::internal::kEmptyString) {
    rcode_ = new ::std::string;
  }
  return rcode_;
}
inline ::std::string* Package::release_rcode() {
  clear_has_rcode();
  if (rcode_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = rcode_;
    rcode_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional uint32 migrateInst = 12;
inline bool Package::has_migrateinst() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Package::set_has_migrateinst() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Package::clear_has_migrateinst() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Package::clear_migrateinst() {
  migrateinst_ = 0u;
  clear_has_migrateinst();
}
inline ::google::protobuf::uint32 Package::migrateinst() const {
  return migrateinst_;
}
inline void Package::set_migrateinst(::google::protobuf::uint32 value) {
  set_has_migrateinst();
  migrateinst_ = value;
}

// optional uint64 targetZHT = 13;
inline bool Package::has_targetzht() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void Package::set_has_targetzht() {
  _has_bits_[0] |= 0x00001000u;
}
inline void Package::clear_has_targetzht() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void Package::clear_targetzht() {
  targetzht_ = GOOGLE_ULONGLONG(0);
  clear_has_targetzht();
}
inline ::google::protobuf::uint64 Package::targetzht() const {
  return targetzht_;
}
inline void Package::set_targetzht(::google::protobuf::uint64 value) {
  set_has_targetzht();
  targetzht_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_meta_2eproto__INCLUDED
